plugins {
    id 'java'
}

group 'ru.netology'
version '1.0-SNAPSHOT'

sourceCompatibility = 11

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.0'
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'com.google.code.gson:gson:2.10.1'
}

test {
    useJUnitPlatform()
}